#!/usr/bin/env node

/**
 * Script to automatically rebuild the chatbot knowledge base from source documents
 *
 * Usage: npm run update-knowledge
 *
 * This script reads all .txt files from src/docs/ and generates src/data/knowledgeBase.js
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DOCS_DIR = path.join(__dirname, '../src/docs');
const OUTPUT_FILE = path.join(__dirname, '../src/data/knowledgeBase.js');

console.log('🔄 Updating chatbot knowledge base...\n');

try {
  // Read all document files
  const doc1 = fs.readFileSync(path.join(DOCS_DIR, 'A BRIEF HISTORY OF THE BIBLE FELLOWSHIP CHURCH.txt'), 'utf8');
  const doc2 = fs.readFileSync(path.join(DOCS_DIR, 'Knowledge Document for the Ask New Life Gem.txt'), 'utf8');
  const doc3 = fs.readFileSync(path.join(DOCS_DIR, 'Summary of BFC AOF and BPL.txt'), 'utf8');
  const doc4 = fs.readFileSync(path.join(DOCS_DIR, 'MEN AND WOMEN ROLES rev2.txt'), 'utf8');

  console.log('✅ Read all source documents');

  // Create the knowledge base file content
  const knowledgeBaseContent = `// Complete knowledge base for Ask New Life chatbot
// This file is AUTO-GENERATED by scripts/updateKnowledgeBase.mjs
// To update: edit the .txt files in src/docs/ then run: npm run update-knowledge

export const FULL_KNOWLEDGE_BASE = \`
KNOWLEDGE BASE FOR NEW LIFE BIBLE FELLOWSHIP CHURCH

IMPORTANT: You MUST answer questions based ONLY on the information in the documents below.
If a question cannot be answered from these documents, politely say: "I don't have that specific information in my knowledge base. Please contact the church office at (302)945-8145 or office@newlifebfcde.org for more details."

========================================
DOCUMENT 1: BRIEF HISTORY OF THE BIBLE FELLOWSHIP CHURCH
========================================

${doc1.trim()}

========================================
DOCUMENT 2: NEW LIFE BIBLE FELLOWSHIP CHURCH INFORMATION
========================================

${doc2.trim()}

========================================
DOCUMENT 3: BFC ARTICLES OF FAITH & BIBLICAL PRINCIPLES
========================================

${doc3.trim()}

========================================
DOCUMENT 4: ROLES OF MEN AND WOMEN WITHIN THE CHURCH
========================================

${doc4.trim()}
\`;
`;

  // Write the generated file
  fs.writeFileSync(OUTPUT_FILE, knowledgeBaseContent, 'utf8');

  console.log('✅ Generated knowledge base file');
  console.log(`📁 Location: ${OUTPUT_FILE}`);

  // Calculate and display stats
  const totalSize = doc1.length + doc2.length + doc3.length + doc4.length;
  console.log(`📊 Total knowledge base size: ${totalSize.toLocaleString()} characters`);
  console.log('\n✨ Knowledge base updated successfully!\n');
  console.log('💡 The chatbot will now use the updated content when you refresh your browser.');

} catch (error) {
  console.error('❌ Error updating knowledge base:', error.message);
  process.exit(1);
}
