#!/usr/bin/env node

/**
 * Script to automatically rebuild the chatbot knowledge base from source documents
 *
 * Usage: npm run update-knowledge
 *
 * This script reads all .txt files from src/docs/ and generates src/data/knowledgeBase.js
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DOCS_DIR = path.join(__dirname, '../src/docs');
const OUTPUT_FILE = path.join(__dirname, '../src/data/knowledgeBase.js');

console.log('🔄 Updating chatbot knowledge base...\n');

try {
  // Read all .txt files from the docs directory automatically
  const files = fs.readdirSync(DOCS_DIR).filter(file => file.endsWith('.txt'));

  if (files.length === 0) {
    throw new Error('No .txt files found in src/docs/');
  }

  const documents = files.map(file => ({
    name: file.replace('.txt', ''),
    content: fs.readFileSync(path.join(DOCS_DIR, file), 'utf8').trim()
  }));

  console.log(`✅ Read ${documents.length} source documents:`)
  documents.forEach((doc, i) => console.log(`   ${i + 1}. ${doc.name}`));

  // Create the knowledge base file content
  const documentSections = documents.map((doc, index) => `
========================================
DOCUMENT ${index + 1}: ${doc.name.toUpperCase()}
========================================

${doc.content}
`).join('\n');

  const knowledgeBaseContent = `// Complete knowledge base for Ask New Life chatbot
// This file is AUTO-GENERATED by scripts/updateKnowledgeBase.mjs
// To update: edit the .txt files in src/docs/ then run: npm run update-knowledge

export const FULL_KNOWLEDGE_BASE = \`
KNOWLEDGE BASE FOR NEW LIFE BIBLE FELLOWSHIP CHURCH

IMPORTANT: You MUST answer questions based ONLY on the information in the documents below.
If a question cannot be answered from these documents, politely say: "I don't have that specific information in my knowledge base. Please contact the church office at (302)945-8145 or office@newlifebfcde.org for more details."
${documentSections}
\`;
`;

  // Write the generated file
  fs.writeFileSync(OUTPUT_FILE, knowledgeBaseContent, 'utf8');

  console.log('✅ Generated knowledge base file');
  console.log(`📁 Location: ${OUTPUT_FILE}`);

  // Calculate and display stats
  const totalSize = documents.reduce((sum, doc) => sum + doc.content.length, 0);
  console.log(`📊 Total knowledge base size: ${totalSize.toLocaleString()} characters`);
  console.log('\n✨ Knowledge base updated successfully!\n');
  console.log('💡 The chatbot will now use the updated content when you refresh your browser.');

} catch (error) {
  console.error('❌ Error updating knowledge base:', error.message);
  process.exit(1);
}
